-- Module F — follow-up / stale-lead / digest notification types + per-user prefs.
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_DUE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_OVERDUE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'STALE_LEAD';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_DUE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_OVERDUE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RENEWAL_DUE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DAILY_DIGEST';

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "settings" JSONB NOT NULL DEFAULT '{}';
